version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: taskmanager_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskmanager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: